# -*- coding: utf-8 -*-
"""buscaBinaria.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1vSM-3ul3VNwEw2EqxcYWB0YntR0-BFGv
"""

def Busca_Binaria (lista, item):
  baixo=0
  alto= len(lista)-1

  while baixo <= alto:
      meio= (baixo + alto)// 2
      chute= lista[meio]

      if chute == item:
        return meio
      if chute > item:
        alto = meio -1

      else: baixo = meio + 1
  return None

minha_lista= [1,3,5,7,9]
print(Busca_Binaria(minha_lista, 3))
print(Busca_Binaria(minha_lista, -1))